title: Amanda's Emporium
email: info@amandasemporium.co.uk
description: WRITE SOMETHING
baseurl: ""
url: ""

collections:
  events:
    output: false
  bears:
    output: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
